"""Added ip_address, serial_number, and service_tag columns to Asset table

Revision ID: 73c27226728b
Revises: 27fa57a8cc3a
Create Date: 2023-06-19 21:10:50.273358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73c27226728b'
down_revision = '27fa57a8cc3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ip_address', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('serial_number', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('service_tag', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.drop_column('service_tag')
        batch_op.drop_column('serial_number')
        batch_op.drop_column('ip_address')

    # ### end Alembic commands ###

