"""Changed Asset column structure to allow for differing 'asset types' and code to check constraints.

Revision ID: b74317359289
Revises: a9cfca60f7fc
Create Date: 2023-09-28 20:29:17.439578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b74317359289'
down_revision = 'a9cfca60f7fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('asset_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('server_ip_address', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('pc_ram', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('pc_processor', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('phone_number', sa.String(length=15), nullable=True))
        batch_op.add_column(sa.Column('mac_address', sa.String(length=15), nullable=True))
        batch_op.add_column(sa.Column('switch_ports', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('switch_poe', sa.Boolean(), nullable=True))
        batch_op.drop_column('url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
        batch_op.drop_column('switch_poe')
        batch_op.drop_column('switch_ports')
        batch_op.drop_column('mac_address')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('pc_processor')
        batch_op.drop_column('pc_ram')
        batch_op.drop_column('server_ip_address')
        batch_op.drop_column('asset_type')

    # ### end Alembic commands ###

