"""Adjusted user_company relationship table for many-to-many relationship between users and companies

Revision ID: ed1c9b031630
Revises: 73c27226728b
Create Date: 2023-07-04 21:39:07.973059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed1c9b031630'
down_revision = '73c27226728b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_constraint('company_name_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.create_unique_constraint('company_name_key', ['name'])

    # ### end Alembic commands ###

